### ISSUE TITLE
couldnt register

### ISSUE THREAD

**Issue by msmci** [Aquarius-blake/The_Hive#21]
checked apk and tried to register but couldnt register
![Screenshot_2023 12 12_01 31 10 489](https://github.com/Aquarius-blake/The_Hive/assets/102038721/7c5a7dd3-a180-4e0c-b59c-1cb2551c9738)

**Comment by Aquarius-blake** [comment]
Greetings, 

Hello and thank you for bringing this to our attention! We appreciate your feedback regarding the registration process. It seems there's a challenge with the registration flow, where the absence of a profile picture prevents user data from being stored.

Trying to create another account with the email in question will result in the "Registration Failed" error message because the account already exists.This is a bug which will most likely be fixed in a later build/update. For now account deletion is not available in-app for users(but might be in the future), however i can delete the account if the email used is provided
